openapi: 3.0.3
info:
  title: Smart Car Ads API - Brands & Models
  version: '1.0'
servers:
  - url: /api/v1
paths:
  /brands:
    get:
      summary: List brands
      x-permissions:
        roles: ["public"]
        scopes: ["brands.read"]
      responses:
        '200':
          description: Brands list
          content:
            application/json:
              examples:
                sample:
                  value:
                    success: true
                    data:
                      - id: 1
                        name_en: "Toyota"
                        name_ar: "تويوتا"
    post:
      summary: Create brand (admin)
      security:
        - bearerAuth: []
      x-permissions:
        roles: ["admin"]
        scopes: ["brands.create"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BrandCreate'
      responses:
        '201':
          description: Created
  /brands/{brandId}/models:
    get:
      summary: List models for brand
      x-permissions:
        roles: ["public"]
        scopes: ["models.read"]
      parameters:
        - in: path
          name: brandId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Models list
    post:
      summary: Create model for brand (admin)
      security:
        - bearerAuth: []
      x-permissions:
        roles: ["admin"]
        scopes: ["models.create"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModelCreate'
      responses:
        '201':
          description: Created
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    BrandCreate:
      type: object
      required: [name_en, name_ar]
      properties:
        name_en:
          type: string
        name_ar:
          type: string
    ModelCreate:
      type: object
      required: [name_en, name_ar]
      properties:
        name_en:
          type: string
        name_ar:
          type: string
        year_from:
          type: integer
        year_to:
          type: integer