openapi: 3.0.3
info:
  title: Smart Car Ads API - Caishha
  version: '1.0'
servers:
  - url: /api/v1
paths:
  /caishha:
    post:
      summary: Create a Caishha ad (offers-first)
      security:
        - bearerAuth: []
      x-permissions:
        roles: ["individual","dealer","showroom"]
        scopes: ["caishha.create"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CaishhaCreate'
            examples:
              sample:
                value:
                  title: "Looking for a 2016 SUV"
                  description: "Need a family SUV with 3rd row"
                  city_id: 10
                  country_id: 1
                  offers_window_period_days: 7
                  media_ids: [150]
      responses:
        '201':
          description: Created
          content:
            application/json:
              examples:
                created:
                  value:
                    success: true
                    data:
                      id: 7777
    get:
      summary: List Caishha ads
      x-permissions:
        roles: ["public"]
        scopes: ["caishha.read"]
      parameters:
        - in: query
          name: page
          schema:
            type: integer
      responses:
        '200':
          description: Paginated list
  /caishha/{adId}:
    get:
      summary: Get Caishha details
      x-permissions:
        roles: ["public"]
        scopes: ["caishha.read"]
      parameters:
        - in: path
          name: adId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Details
    put:
      summary: Update Caishha ad
      security:
        - bearerAuth: []
      x-permissions:
        roles: ["individual","dealer","showroom","admin"]
        scopes: ["caishha.update.own","caishha.update.any"]
      responses:
        '200':
          description: Updated
    delete:
      summary: Delete Caishha ad
      security:
        - bearerAuth: []
      x-permissions:
        roles: ["individual","dealer","showroom","admin"]
        scopes: ["caishha.delete.own","caishha.delete.any"]
      responses:
        '204':
          description: Deleted
  /caishha/{adId}/offers:
    post:
      summary: Create an offer on Caishha ad
      security:
        - bearerAuth: []
      x-permissions:
        roles: ["dealer","showroom","marketer"]
        scopes: ["caishha.offers.create"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CaishhaOfferCreate'
      responses:
        '201':
          description: Offer created
    get:
      summary: List offers for Caishha ad
      x-permissions:
        roles: ["admin","individual","dealer","showroom"]
        scopes: ["caishha.offers.read"]
      parameters:
        - in: path
          name: adId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Offers list
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CaishhaCreate:
      type: object
      required: [title, description, city_id, country_id]
      properties:
        title:
          type: string
        description:
          type: string
        offers_window_period_days:
          type: integer
        media_ids:
          type: array
          items:
            type: integer
    CaishhaOfferCreate:
      type: object
      required: [ad_id, price]
      properties:
        ad_id:
          type: integer
        price:
          type: number
        comment:
          type: string