openapi: 3.0.3
info:
  title: Smart Car Ads API - Offers
  version: '1.0'
servers:
  - url: /api/v1
paths:
  /offers:
    post:
      summary: Create an offer (generic resource for Caishha/other offers)
      security:
        - bearerAuth: []
      x-permissions:
        roles: ["dealer","showroom","marketer"]
        scopes: ["offers.create"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OfferCreate'
      responses:
        '201':
          description: Offer created
          content:
            application/json:
              examples:
                sample:
                  value:
                    ad_id: 9991
                    price: 8200
                    comment: "Can deliver within 3 days"
    get:
      summary: List offers (admin/owner)
      x-permissions:
        roles: ["admin","owner"]
        scopes: ["offers.read"]
      parameters:
        - in: query
          name: page
          schema:
            type: integer
      responses:
        '200':
          description: Paginated offers
          content:
            application/json:
              examples:
                sample:
                  value:
                    success: true
                    data:
                      page: 1
                      per_page: 20
                      total: 1
                      items:
                        - id: 555
                          ad_id: 9991
                          price: 8200
  /offers/{offerId}:
    get:
      summary: Get offer details
      parameters:
        - in: path
          name: offerId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Offer details
    put:
      summary: Update offer
      security:
        - bearerAuth: []
      x-permissions:
        roles: ["dealer","showroom","admin"]
        scopes: ["offers.update.own","offers.update.any"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OfferUpdate'
      responses:
        '200':
          description: Updated
    delete:
      summary: Delete offer
      security:
        - bearerAuth: []
      x-permissions:
        roles: ["dealer","showroom","admin"]
        scopes: ["offers.delete.own","offers.delete.any"]
      responses:
        '204':
          description: Deleted
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    OfferCreate:
      type: object
      required: [ad_id, price]
      properties:
        ad_id:
          type: integer
        price:
          type: number
        comment:
          type: string
    OfferUpdate:
      type: object
      properties:
        price:
          type: number
        comment:
          type: string