openapi: 3.0.3
info:
  title: Smart Car Ads API - Packages
  version: '1.0'
servers:
  - url: /api/v1
paths:
  /packages:
    get:
      summary: List available packages (public)
      x-permissions:
        roles: ["public"]
        scopes: ["packages.read"]
      parameters:
        - in: query
          name: page
          schema:
            type: integer
      responses:
        '200':
          description: Packages list
    post:
      summary: Create package (admin)
      security:
        - bearerAuth: []
      x-permissions:
        roles: ["admin","super_admin"]
        scopes: ["packages.create"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PackageCreate'
            examples:
              sample:
                value:
                  name: "Dealer Pro"
                  description: "50 normal ads + 10 featured"
                  price: 199.99
                  duration_days: 30
      responses:
        '201':
          description: Package created
  /packages/{packageId}:
    get:
      summary: Get package details
      parameters:
        - in: path
          name: packageId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Package details
    put:
      summary: Update package (admin)
      security:
        - bearerAuth: []
      x-permissions:
        roles: ["admin","super_admin"]
        scopes: ["packages.update"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PackageUpdate'
      responses:
        '200':
          description: Updated
    delete:
      summary: Delete package (admin)
      security:
        - bearerAuth: []
      x-permissions:
        roles: ["admin","super_admin"]
        scopes: ["packages.delete"]
      responses:
        '204':
          description: Deleted
  /users/{userId}/packages:
    get:
      summary: List packages owned by user
      security:
        - bearerAuth: []
      x-permissions:
        roles: ["individual","dealer","showroom","admin"]
        scopes: ["packages.read.own","packages.read.any"]
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User packages
  /packages/{packageId}/assign:
    post:
      summary: Assign package to a user (admin)
      security:
        - bearerAuth: []
      x-permissions:
        roles: ["admin"]
        scopes: ["packages.assign"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [user_id]
              properties:
                user_id:
                  type: integer
                start_date:
                  type: string
                  format: date
      responses:
        '200':
          description: Assigned
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    PackageCreate:
      type: object
      required: [name, price, duration_days]
      properties:
        name:
          type: string
        description:
          type: string
        price:
          type: number
        duration_days:
          type: integer
        features:
          type: object
    PackageUpdate:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        price:
          type: number
        duration_days:
          type: integer
        features:
          type: object
    PackageResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
        duration_days:
          type: integer
        active:
          type: boolean