openapi: 3.0.3
info:
  title: Smart Car Ads API - Unique Ads
  version: '1.0'
servers:
  - url: /api/v1
paths:
  /unique-ads:
    post:
      summary: Create a unique ad
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UniqueAdCreate'
      responses:
        '201':
          description: Created
    get:
      summary: List unique ads (owner/admin scope)
      parameters:
        - in: query
          name: page
          schema:
            type: integer
      responses:
        '200':
          description: Paginated list
  /unique-ads/{adId}:
    get:
      summary: Get unique ad details
      parameters:
        - in: path
          name: adId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Ad details
    put:
      summary: Update unique ad
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UniqueAdUpdate'
      responses:
        '200':
          description: Updated
    delete:
      summary: Delete unique ad
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Deleted
  /unique-ads/{adId}/actions/feature:
    post:
      summary: Promote/feature a unique ad
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Featured
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UniqueAdCreate:
      type: object
      required: [title, description, category_id, city_id, country_id]
      properties:
        title:
          type: string
        description:
          type: string
        banner_image_id:
          type: integer
        banner_color:
          type: string
        is_verified_ad:
          type: boolean
        media_ids:
          type: array
          items:
            type: integer
    UniqueAdUpdate:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        is_verified_ad:
          type: boolean
        media_ids:
          type: array
          items:
            type: integer